### ISSUE TITLE
modifiedWriteValues ignored in patches

### ISSUE THREAD

**Issue by kossnikita** [rust-embedded/svdtools#156]
#106  added support for modifiedWriteValues but this ignored in patches

```yaml
  SCR:
    _modify:
      IOSB0:
        access: write-only
        modifiedWriteValues: oneToClear
```

```xml
            <field>
              <name>IOSB0</name>
              <description>Set bit 0</description>
              <bitOffset>0</bitOffset>
              <bitWidth>1</bitWidth>
              <access>write-only</access> << it works
            </field>
```

**Comment by burrbull** [comment]
https://github.com/stm32-rs/stm32-rs/blob/da9085da570e8934b205115f128500c27ca721fb/peripherals/flash/flash_v1.yaml#L8-L10

**Comment by kossnikita** [comment]
Yes, I do it like in this example. Why doesn't this patch work? Doesn't this provide an advantage when used with svd2rust?

**Comment by burrbull** [comment]
How looks your patch? Have you added `_W1C`?

**Comment by kossnikita** [comment]
Oh. Thank you. This is not at all the behavior I expected.

```yaml
    RLDF:
      _read:
        NotReached: [0, "Downcounter doesn't reached 0x40"]
        Reached: [1, "Downcounter reached 0x40"]
      _W1C:
        Clear: [1, "Clear flag"]
```

```xml
<modifiedWriteValues>zeroToClear</modifiedWriteValues>
              <enumeratedValues>
                <name>RLDFR</name>
                <usage>read</usage>
                <enumeratedValue>
                  <name>NotReached</name>
                  <description>Downcounter doesn't reached 0x40</description>
                  <value>0</value>
                </enumeratedValue>
                <enumeratedValue>
                  <name>Reached</name>
                  <description>Downcounter reached 0x40</description>
                  <value>1</value>
                </enumeratedValue>
              </enumeratedValues>
              <enumeratedValues>
                <name>RLDFW</name>
                <usage>write</usage>
                <enumeratedValue>
                  <name>Clear</name>
                  <description>Clear flag</description>
                  <value>0</value>
                </enumeratedValue>
              </enumeratedValues>
```
