### ISSUE TITLE
Panic in field array dim calculation

### ISSUE THREAD

**Issue by kossnikita** [rust-embedded/svdtools#161]
```yaml
EXINT:
  INTEN:
    _array:
      INTEN?,INTEN10:
        description: "Interrupt enable or disable on line %s"
```
Token boundaries are calculated without comma split.

https://github.com/rust-embedded/svdtools/blob/27cf2b136627e7fad154b66d4295b10e3fa02682/src/patch/register.rs#L361

```
li = 5, ri = 8
thread 'main' panicked at 'byte index 18446744073709551614 is out of bounds of `INTEN0`', src\patch\register.rs:383:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

https://github.com/rust-embedded/svdtools/blob/27cf2b136627e7fad154b66d4295b10e3fa02682/src/patch/register.rs#L383

**Comment by burrbull** [comment]
I know about this issue, but I don't know good way to fix it.

**Comment by burrbull** [comment]
#161 should help for your specific situation, but this is just a patch.

**Comment by burrbull** [comment]
Although this can break other use cases.

**Comment by kossnikita** [comment]
Yes, works in this case

```yaml
EXINT:
  INTEN:
    _array:
      INTEN?,INTEN1[0-7]:
        description: "Interrupt enable or disable on line %s"
```

```xml
<fields>
  <field>
    <dim>18</dim>
    <dimIncrement>0x1</dimIncrement>
    <dimIndex>0-17</dimIndex>
    <name>INTEN%s</name>
    <description>Interrupt enable or disable on line %s</description>
```

But don't work there (I don't know why someone would write such a weird patch)

```yaml
EXINT:
  INTEN:
    _array:
      INTEN1[0-7],INTEN?:
        description: "Interrupt enable or disable on line %s"
```

```xml
<fields>
  <field>
    <dim>18</dim>
    <dimIncrement>0x1</dimIncrement>
    <dimIndex>,,,,,,,,,,0,1,2,3,4,5,6,7</dimIndex>
    <name>INTEN1%s</name>
    <description>Interrupt enable or disable on line %s</description>
```
