### ISSUE TITLE
cannot _derive from a register that is affected by a _cluster modification

### ISSUE THREAD

**Issue by simpkins** [rust-embedded/svdtools#226]
I'm trying to make a patch to clean up the peripherals in the ESP32 USB0 peripheral.  It has registers for several endpoints that need to be clustered, and I also want to make some of the registers derive from other registers.  svdtools currently doesn't appear to allow me to both apply clustering and make derivedFrom modifications at the same time.

If I add a `_derive` section, these changes appear to take be applied before the `_cluster` section.  When the `_derive` changes are made it checks that the derivedFrom register names are valid.  However, these register names are later changed by the `_cluster` operation, which makes svdtools generate an invalid SVD files since the `derivedFrom` fields refer to the old names.  I can't use the new names in the `_derive` section, since svdtools rejects them as invalid since they don't exist yet when the check is made.

In theory I suppose svdtools should track all `derivedFrom` attributes throughout the SVD file, and update them correctly whenever it renames/clusters/derives a register that is the destination of an existing `derivedFrom` attribute.  This seems possibly more complicated than it is worth, however.  Alternatively, it would be nice if there were an easy way to force svdtools to skip the register name check in `_derive`, so I could specify the desired `derivedFrom` name without svdtools complaining because it doesn't exist yet.

Here is a with more details about what I would like to accomplish
https://github.com/esp-rs/esp-pacs/pull/213/files/e36f054438d1a2a44e81f24eea4efae80ea861e0#r1550642332

**Comment by burrbull** [comment]
> In theory I suppose svdtools should track all `derivedFrom` attributes throughout the SVD file, and update them correctly whenever it renames/clusters/derives a register that is the destination of an existing `derivedFrom` attribute.

Yeah. Maybe.

Could you first try 2 other ways to `_derive` after `_cluster`:
1. Use `_derive` inside `_cluster` like:
```yaml
PER1:
  _cluster:
    CNAME%s:
       REG1: {}
       REG2: {}
       _derive:
           REG3: REG1
```
2. Split on 2 peripheral rule blocks (with different headers which match same peripheral):
```yaml
PER1:
  _cluster:
    CNAME%s:
       REG1: {}
       REG2: {}
"PER[1]":
   "CNAME%s":
       _derive:
           REG3: REG1
```
