### ISSUE TITLE
Clarification on how to create a cluster, while adding a peripheral.

### ISSUE THREAD

**Issue by Frostie314159** [rust-embedded/svdtools#248]
Hi, I'm trying to write an SVD patch to add a peripheral, and I have a set of registers, which repeats five times. I'm trying to create a cluster of those, however the documentation is very unspecific on how to do that.

**Comment by burrbull** [comment]
It is not possible to do directly (not implemented yet).

But you can create peripheral and then add cluster into existent peripheral:
```yaml
_add:
  PER:
     baseAddress: xx
     xx: xx

PER:
  _add:
    _clusters:
      CL%s:
        dim: xx
        xx: xx
```
