### ISSUE TITLE
_strip doesn't seem to work on cluster names

### ISSUE THREAD

**Issue by cosmikwolf** [rust-embedded/svdtools#249]
given the SVD:

```xml
<peripheral>
    <cluster>
      <dim>1</dim>
      <dimIncrement>0xFC</dimIncrement>
      <dimArrayIndex/>
      <name>CANFD0_MCAN[%s]</name>
      <addressOffset>0x7000</addressOffset>
      <register>
        ...
      </register>
</peripheral>
```

This doesn't strip the prefix from the title of the cluster:
```yaml
"CANFD0":
  _strip:
    - "CANFD?_"
  _clusters:
    "CANFD*":
      _strip:
        - "CANFD?_"
```

It does work on the registers within the cluster, just not the cluster itself.

Same SVD file as in this issue:
https://github.com/rust-embedded/svdtools/issues/245
