### ISSUE TITLE
There is no way to define enumerated values

### ISSUE THREAD

**Issue by bugadani** [rust-embedded/svdtools#256]
The enumeratedValues key is ignored in register fields.

**Comment by burrbull** [comment]
`svdtools` **was created** to add `enumeratedValues`. See [README](https://github.com/rust-embedded/svdtools?tab=readme-ov-file#device-and-peripheral-yaml-format)

**Comment by bugadani** [comment]
I see, so the expected workflow when defining new peripherals is, to first add the peripheral without enumerated values, then modify it immediately? I was hoping to do something like the following, since most of the other properties work like this:

```yaml
  field:
    description: "foo"
    ...
    enumeratedValues:
      ...
```
