### ISSUE TITLE
No way to add enumerated values when adding a register

### ISSUE THREAD

**Issue by shaydonb** [rust-embedded/svdtools#275]
```yaml
PERIPHERAL_NAME
    _add:
        REGISTER_NAME: 
            description: "This descrribes what the register does." 
            addressOffset: 0x4 
            resetValue: 0x0 
            bitWidth: 32 
            access: read-write 
            fields: 
                FIELD_NAME: 
                    description: "This describes what the field does." 
                    bitOffset: 0 
                    bitWidth: 1 
                    access: read-write 
                    enumeratedValues: 
                        ENUM_NAME: 
                            enumeratedValue: 
                                Disabled: # [0, "Disable receive data interrupt"] 
                                    value: 0 
                                Enabled: # [1, "Enable receive data interrupt"] 
                            value: 1
                    # _enum:
                    #     Disabled: [0, "Disable receive data interrupt"]
                    #     Enabled: [1, "Enable receive data interrupt"]
```

The above snipped does generate a register, but does not generate any enum fields within that register as I would expect.
From what I can tell when perusing the source code, this appears to be due to a lack of recursion to recognize dim child elements to add when building the register:
https://github.com/rust-embedded/svdtools/blob/master/src/patch/mod.rs#L411-L445

Is this a correct root cause (lack of recursion when building dim elements? If there is a way to accomplish what I'm trying to with the code written as is (besides separating out a new file to edit the output of the first, which is my workaround for now)? Thanks in advance for taking a glance at this.
