### ISSUE TITLE
Allow adding derivedFrom attribute to enumeratedValues

### ISSUE THREAD

**Issue by qwandor** [rust-embedded/svdtools#62]
As far as I can tell, there is no way to use the svd patch tool to add a `derivedFrom` attribute to an `enumeratedValues` tag. This should be possible. I would like to do this so that `svd2rust` uses the same enum type for the equivalent field on several different peripherals. I would expect to be able to do something like

```yaml
TIMER2:
  CHCTL2:
    _derive:
      CH0P: TIMER0.CHCTL2.CH0P
```

Or perhaps:

```yaml
TIMER2:
  CHCTL2:
    _modify:
      CH0P:
        derivedFrom: TIMER0.CHCTL2.CH0P
```

But neither of these seem to work at the moment.

**Comment by qwandor** [comment]
It turns out this is already possible, it's just not documented and I had to read the source to figure it out. I was able to do what I what I wanted like:

```yaml
TIMER2:
  CHCTL2:
    CH0P:
      _derivedFrom: "TIMER0.CHCTL2.CH0P.CH0P"
```

So it would be good to document this. It's also not clear why the field name has to be repeated twice.
